### ISSUE TITLE
If description is empty for a key, the UI won't load it

### ISSUE THREAD

**Issue by ch3ckmat3** [apinprastya/flutter-internationalize#11]
Great initiative, I must say 👍

**A small bug:**
If you leave the description empty, the entry is saved, but then if you refresh the UI, or restart VS Code, any key with empty description won't be loaded in the extension UI.

**Comment by masonzhang** [comment]
Thanks a lot for the fixing. I'm wondering when a new release will be published for vs code?

**Comment by apinprastya** [comment]
Hi @masonzhang, I was unable to publish the plugin, I always get timeout error when doing it. So, i am not really sure how to fix the timeout error.

![Screenshot from 2020-01-12 16-20-42](https://user-images.githubusercontent.com/1171479/72216718-9ebf8580-3557-11ea-98cd-1f4f61d743c9.png)

**Comment by masonzhang** [comment]
Thanks a lot for the reply. Anything I can help?

**Comment by apinprastya** [comment]
plugin published

**Comment by ch3ckmat3** [comment]
works like a charm. Thank you!
