### ISSUE TITLE
Add property for each group class to get translation dynamically

### ISSUE THREAD

**Issue by ngdminh93** [apinprastya/flutter-internationalize#19]
the extension is great, but I have to manually add these line every time generate dart file. Could you mind consider to add this

class Localemain {
...

String byText(String langCode) {
    try {
      return _data[langCode];
    } catch (e) {}
    return '';
  }
}

**Comment by apinprastya** [comment]
added method 

```
String getByKey(String key) {
  return _data[key];
}
```
