### ISSUE TITLE
stuck on loading 

### ISSUE THREAD

**Issue by alfaruqrizqi18** [apinprastya/flutter-internationalize#7]
I have used before, and when I exit my vscode, then I reopen my project and I open flutter internationalize packages it's stuck on loading 
![image](https://user-images.githubusercontent.com/43517239/63236927-094eec80-c26a-11e9-98fb-a29ce8d6e16a.png)

**Comment by alfaruqrizqi18** [comment]
but when I rename my existing `locales` folder and reopen flutter internationalize, it's works well.
flutter internationalize create new folder `locales`. Please make checking feature for existing `locales` and load it to flutter internationalize instead create new ones.

**Comment by apinprastya** [comment]
I have made some breaking file structure in the past (not sure which version), this happen possible because you have old version of json file.

Can you please check again when it already generated the files, are you able to edit and reopen again? If it everything work well, then your json files inside the locales folder is using old structure.

**Comment by alfaruqrizqi18** [comment]
Yes, I have my language json files. I want to load it to flutter internationalize again. How to do it?
![image](https://user-images.githubusercontent.com/43517239/63238173-584b5080-c26f-11e9-8ed8-552d6a50bd99.png)

**Comment by apinprastya** [comment]
Tinggal buka extensionnya lagi mas, "Ctrl + Shift + P" lalu buka "Flutter-International - Open".
Kalau enggak bisa tolong infokan sistem operasinya pakai apa? saya pakai Linux dan MacOS aman tidak ada kendala.

**Comment by alfaruqrizqi18** [comment]
Oh bisa bhs indo hehe
Sudah mas, tp ttp kyk foto diatas, stuck loading
Saya pake win 10 pro 1809

![image](https://user-images.githubusercontent.com/43517239/63238313-048d3700-c270-11e9-9cbe-12cde05de700.png)

**Comment by apinprastya** [comment]
Kalau di tekan tombol refresh tetep juga mas?
Nanti coba saya check mas, sedang tidak ada windows saat ini.

**Comment by alfaruqrizqi18** [comment]
tetep juga mas, tp pas saya coba ganti nama folder locales itu ke locales2 terus saya buka flutter intl nya dia lgsg work bikin folder default locales

oke mas thank u

**Comment by apinprastya** [comment]
Mas setelah saya telaah, kemungkinan itu kejadian karena di dalam project ada folder "locales".

**Comment by alfaruqrizqi18** [comment]
iya mas, jadi kan project flutter saya udah saya bikinkan 2 bahasa lwt lib ini minggu kmrn
hari ini saya pgn ngedit bahasanya dan mau saya tambahin, pas sy buka ttp loading.

**Comment by apinprastya** [comment]
Barusan saya update versi (0.1.2) terbaru, silakan check mas. Mohon kabar bisa atau enggak

**Comment by alfaruqrizqi18** [comment]
Oke mas apin. Terima kasih besok saya coba...

**Comment by alfaruqrizqi18** [comment]
Saya barusan sudah update mas ke yang terbaru.
1. Folder locales lama masih ada 
2. Saya buka flutter inter masih ttp stuck loading
3. Pas folder locales saya rename menjadi locales123123, saya buka flutter int lg
4. Otomatis bikin locales baru, tp di jendelanya masih loading. Setelah saya refresh baru muncul group sama key nya.

**Comment by apinprastya** [comment]
Sepertinya Anda membuka beberapa project bersamaan dalam 1 VS code. Extension saya cuma bisa baca 1 folder proyek dalam 1 workspace

**Comment by apinprastya** [comment]
this should be fixed on 0.1.3 as already support multi folders on the workspace

**Comment by alfaruqrizqi18** [comment]
Nanti sy coba lg mas
Sy buka 1 project dalam 1 workspace
