### ISSUE TITLE
Excel export truncates some of the text

### ISSUE THREAD

**Issue by nicodumdum** [apinprastya/flutter-internationalize#9]
I have some keys that have multi-paragraph text.
The texts display fine in the app.
Unfortunately, when I exported it, most of the text for all languages became truncated.

Flutter Internationalize:
![Annotation 2019-11-08 152049](https://user-images.githubusercontent.com/1650987/68457662-c46c9d80-023b-11ea-8824-f0a6f03b87b8.png)

Exported Excel File:
![Annotation 2019-11-08 152222](https://user-images.githubusercontent.com/1650987/68457673-cb93ab80-023b-11ea-9a27-d1c274a14a2e.png)

**Comment by apinprastya** [comment]
Can you please provide me the minimal way to repro this? I tried on my side with long text and the issue you reported not happen on my side

**Comment by nicodumdum** [comment]
I can give you my working files so you can try it yourself.
[locales.zip](https://github.com/apinprastya/flutter-internationalize/files/3824730/locales.zip)

**Comment by apinprastya** [comment]
Thanks for your reply, I tried on my side and everything just fine.

![Screenshot from 2019-11-08 20-35-47](https://user-images.githubusercontent.com/1171479/68480460-7a011600-0267-11ea-8766-7e39f53e9d3a.png)

**Comment by nicodumdum** [comment]
I finally found the issue. But first, I just wanna give you a brief background on what I was working with. I was working with 2 Windows 10 units. One without Microsoft Office installed and one with Microsoft Office installed. The first time I tried the Excel Export function was with the unit without the Microsoft Office installed. When I realized the truncate issue, I first thought that maybe because I didn't have Microsoft Office installed, which I knew was a very weird assumption since the file already exported successfully. So I tried exporting on the unit with the Microsoft Office installed, but still same truncated result. What boggled me even more was when I gave you my working files and you still got not issues. So I went back on what was probably wrong in the way I exported it. Then I realized that when saving the file as `Spreadsheet`, you have two file extension options, `.xls` and `.xlsx`. When saving the file without specifying the file extension, it defaults to `.xls`. I also noticed that you also opened it as `.xls` and it worked fine on your side. So, I tried saving it as `.xlsx` instead.
<img width="710" alt="Annotation 2019-11-10 215357" src="https://user-images.githubusercontent.com/1650987/68545147-36dca980-0405-11ea-9bc1-09c79cfe4508.png">
Then when I opened it in Excel, lo and behold, all the text were finally there.
<img width="1085" alt="Annotation 2019-11-10 214558" src="https://user-images.githubusercontent.com/1650987/68545209-d13ced00-0405-11ea-9b5b-5fdd2fb03797.png">
Now, realized it was after all just a file extension issue that was probably causing Excel not to read all the text properly.

I am now closing this issue since I already found the solution. Although if I may advice that you should probably include in your documentation or read.me file that it's better to export in the `.xlsx` format if you're going to open the file using Microsoft Office Excel since it currently defaults to `.xls`.

PS: I'm using Microsoft Office 365 with Excel version 16
